# version: '3.4'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Senha10adaps
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - farias-network
  rest-with-spring-boot-and-java:
    image: marcelofarias2022/rest-with-spring-boot-and-java
    restart: always
    build: .
    working_dir: /rest-with-spring-boot-and-java
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Senha10adaps
    command: mvn spring-boot:run
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - farias-network
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - partainer_data:/data
    networks:
      - farias-network
volumes:
  partainer_data:

networks: 
    farias-network:
        driver: bridge