name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Application .jar
      working-directory: ./rest-with-spring-boot-and-java
      run: mvu clean package

    - name: Docker Compose Build
      working-directory: ./java
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker push marcelofarias2022/rest-with-spring-boot-and-java